# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.4
    disk: 2048

cache:
    type: redis:5.0

search:
    type: solr:8.4
    disk: 1024
    configuration:
        cores:
            dspace:
                conf_dir: !archive "solr/eureka/conf/"
        endpoints:
            main:
                core: dspace
